name: FactionsPro
author: RoseCrib
description: Plugin pentru servere de factions
version: 1.3.20
main: FactionsPro\FactionMain
api: [3.0.0,4.0.0]
softdepend: ["AntiSpamPro"]
extensions: [sqlite3]
commands:
  f:
    description: folosește comanda /f help pentru a vedea comenzile
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Permiteți utilizarea tuturor comenzilor de facțiune"
